### ISSUE TITLE
温艳军同志，注意品行奥，宁接着抄，迟早一天现世报哦

### ISSUE THREAD

**Issue by TY-LIU** [wenyanjun/free-code#22]

**Comment by wenyanjun** [comment]
你TMD是傻逼吧, 我给你免费提供jar还各种喷 有种你别下载, 你自己去网上找个试试

**Comment by wenyanjun** [comment]
网上那么多文章, 有种你一篇一篇都去喷一下啊, SB

**Comment by TY-LIU** [comment]
> 网上那么多文章, 有种你一篇一篇都去喷一下啊, SB

你装什么装啊，是你自己的东西吗，还恬不知耻的放你的收款码，要不要脸啊。而且，下载我也是在人家作者那里下的，你有给人家作者任何流量？没有原创作者的产出，还有你的份？我今天好巧不巧，正好搜了下，看看人作者更新没，结果看到你这种败类，路过肯定是要踩两脚的。

**Comment by TY-LIU** [comment]
就宁还给人家远程呢，也就骗骗小白了。真出了什么技术难题，你有能力解决吗。估计也就：“我也不知道”，“你换个版本试试”，“我给你看看有没有最新的破解包”。哈哈哈哈哈哈，笑skr个人
