### ISSUE TITLE
你在装你妈呢，盗用别人的东西，叫你标注来源，还跑到我的仓库下乱吠

### ISSUE THREAD

**Issue by TY-LIU** [wenyanjun/free-code#23]
![微信截图_20200714160851](https://user-images.githubusercontent.com/29595097/87401333-94587400-c5ec-11ea-942b-9989915da132.png)
牛皮牛皮

**Comment by wenyanjun** [comment]
你个大傻逼 草死你妈的 , 咋地啦

**Comment by wenyanjun** [comment]
傻逼一个

**Comment by wenyanjun** [comment]
大傻逼

**Comment by TY-LIU** [comment]
> 大傻逼

爷在上班，等会下班回去再和你慢慢对线，wink
